const {
  readFileSync,
  writeFileSync,
  readdirSync,
  existsSync,
} = require("node:fs");
const { resolve, relative } = require("node:path");
const { pathToFileURL } = require("node:url");
const { readPackages } = require("./packages.cjs");
const defaultRoot = resolve(__dirname, "..");

function validateMetadata(pkg) {
  const meta = pkg.manifest.mcpSuite;
  const env = meta?.environment;
  if (
    !meta ||
    typeof meta.displayName !== "string" ||
    !meta.displayName.trim() ||
    !/^dist\/(?:[a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_-]+\.js$/.test(
      meta.toolInventory?.module ?? ""
    ) ||
    !/^[a-zA-Z_$][\w$]*$/.test(meta.toolInventory?.export ?? "") ||
    !env ||
    !Array.isArray(env.required) ||
    !Array.isArray(env.optional) ||
    typeof env.notes !== "string"
  )
    throw new Error(`Invalid catalog metadata for ${pkg.server}`);
  const names = [...env.required, ...env.optional];
  if (
    names.some(
      (name) => typeof name !== "string" || !/^[A-Z][A-Z0-9_]+$/.test(name)
    ) ||
    new Set(names).size !== names.length
  )
    throw new Error(`Invalid environment metadata for ${pkg.server}`);
  return meta;
}
function sourceEnvironment(directory) {
  const names = new Set();
  function scan(path) {
    for (const file of readdirSync(path, { withFileTypes: true })) {
      const full = resolve(path, file.name);
      if (file.isDirectory()) scan(full);
      else if (file.name.endsWith(".ts")) {
        const source = readFileSync(full, "utf8");
        const pattern =
          /(?:process\.env\.|get(?:EnvVar|OptionalEnvVar|HttpUrlEnvVar|EnumEnvVar|IntegerEnvVar|BooleanEnvVar)\(\s*["'])([A-Z][A-Z0-9_]*)/g;
        for (const match of source.matchAll(pattern)) names.add(match[1]);
        if (/\bgetLogLevel\(\)/.test(source)) names.add("LOG_LEVEL");
      }
    }
  }
  scan(directory);
  return [...names].sort();
}
async function loadCatalog(root = defaultRoot) {
  const owner = JSON.parse(
    readFileSync(resolve(root, "package.json"), "utf8")
  ).author;
  const servers = [];
  for (const pkg of readPackages(root)) {
    const meta = validateMetadata(pkg);
    if (pkg.manifest.author !== owner)
      throw new Error(`Author mismatch for ${pkg.server}`);
    const declared = [
      ...meta.environment.required,
      ...meta.environment.optional,
    ].sort();
    if (
      JSON.stringify(declared) !==
      JSON.stringify(sourceEnvironment(resolve(pkg.path, "src")))
    )
      throw new Error(
        `Environment inventory differs from source for ${pkg.server}`
      );
    const modulePath = resolve(pkg.path, meta.toolInventory.module);
    const module = await import(pathToFileURL(modulePath).href);
    const definitions = module[meta.toolInventory.export];
    if (
      !Array.isArray(definitions) ||
      definitions.some(
        (tool) => !tool || typeof tool.name !== "string" || !tool.name
      )
    )
      throw new Error(`Invalid tool inventory for ${pkg.server}`);
    const tools = definitions.map((tool) => tool.name).sort();
    if (new Set(tools).size !== tools.length)
      throw new Error(`Duplicate tools for ${pkg.server}`);
    if (
      typeof pkg.manifest.main !== "string" ||
      !pkg.manifest.main.startsWith("dist/") ||
      pkg.manifest.main.includes("..") ||
      !existsSync(resolve(pkg.path, pkg.manifest.main))
    )
      throw new Error(`Missing built entry for ${pkg.server}`);
    if (
      !pkg.manifest.bin ||
      Object.values(pkg.manifest.bin).some((path) => path !== pkg.manifest.main)
    )
      throw new Error(`Binary entry mismatch for ${pkg.server}`);
    servers.push({
      name: pkg.server,
      displayName: meta.displayName,
      package: pkg.manifest.name,
      version: pkg.manifest.version,
      entry: relative(root, resolve(pkg.path, pkg.manifest.main)),
      binaries: Object.keys(pkg.manifest.bin),
      toolCount: tools.length,
      tools,
      environment: meta.environment,
    });
  }
  return {
    schemaVersion: 1,
    generatedFrom:
      "npm workspaces, package mcpSuite metadata and built tool exports",
    servers,
  };
}
function renderCatalog(catalog) {
  const lines = [
    "# Server catalog",
    "",
    "Generated by `npm run catalog:generate`. Edit workspace manifests and tool source,",
    "then regenerate; this file and config/servers.json are inventories, not runtime configuration.",
    "",
    "| Server | Package | Tools | Required at startup |",
    "| --- | --- | ---: | --- |",
  ];
  for (const s of catalog.servers)
    lines.push(
      `| [${s.displayName}](../servers/${s.name}/README.md) | \`${s.package}\` | ${s.toolCount} | ${s.environment.required.map((k) => `\`${k}\``).join(", ") || "None"} |`
    );
  for (const s of catalog.servers)
    lines.push(
      "",
      `## ${s.displayName}`,
      "",
      `Version: \`${s.version}\`. Repository entry: \`${s.entry}\`.`,
      "",
      `Optional/conditional variables: ${s.environment.optional.map((k) => `\`${k}\``).join(", ") || "None"}.`,
      "",
      s.environment.notes,
      "",
      "Tools:",
      "",
      ...s.tools.map((name) => `- \`${name}\``)
    );
  return lines.join("\n") + "\n";
}
async function artifacts(root = defaultRoot) {
  const catalog = await loadCatalog(root);
  const prettier = require("prettier");
  const outputs = {
    "config/servers.json": JSON.stringify(catalog, null, 2) + "\n",
    "docs/server-catalog.md": renderCatalog(catalog),
  };
  for (const [path, text] of Object.entries(outputs))
    outputs[path] = await prettier.format(text, {
      ...(await prettier.resolveConfig(resolve(root, path))),
      filepath: path,
    });
  return outputs;
}
async function checkCatalog(root = defaultRoot) {
  for (const [path, text] of Object.entries(await artifacts(root)))
    if (readFileSync(resolve(root, path), "utf8") !== text)
      throw new Error(`Stale catalog: ${path}; run npm run catalog:generate`);
}
async function main(args = process.argv.slice(2)) {
  if (args.length !== 1 || !["--write", "--check"].includes(args[0]))
    throw new Error("Usage: node scripts/catalog.cjs --write|--check");
  // Compile current sources before deriving inventory; no stale-output assumption.
  require("./build.js").main(["--server=all"]);
  if (args[0] === "--check") await checkCatalog();
  else
    for (const [path, text] of Object.entries(await artifacts()))
      writeFileSync(resolve(defaultRoot, path), text);
}
if (require.main === module)
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
module.exports = {
  validateMetadata,
  sourceEnvironment,
  loadCatalog,
  renderCatalog,
  artifacts,
  checkCatalog,
  main,
};
